package cl
// This is a list of response-headers that the system uses to communicate
var InnerOrder string = "INNER"
var OuterOrder string = "OUTER"
var Floor string = "FLOOR"
var Startup string = "STARTUP"
var Timeout string = "TIMEOUT"
var Stop string = "STOP"
var Move string = "MOVE"
var Up string = "UP"
var Down string = "DOWN"
var Master string = "MASTER"
var Slave string = "SLAVE"
var SetMaster string = "SETMASTER"
var Ping string = "PING"